#!groovy

node('master') {
    stage('Checkout') {
        echo 'Code checkout'        
        git 'http://localhost:3000/basil/MercuryTours.git'
    }
    
    stage('Run tests') {
        echo 'Running tests'
        
        try {
            bat "mvn -f F:\\automation\\jenkins\\.jenkins\\workspace\\functional_tests\\TestAutomationProject\\pom.xml clean test"
        } catch (err) {
            
        } finally {
            publishHTML (target: [
            reportDir: 'target/test-report',
            reportFiles: 'index.html',
            reportName: "Smoke tests report"
            ])
        }
    }
}