pipeline {
	agent any
	stages {
		stage ('Checkout') {
			steps {
				echo 'Code checkout' 
				script {
					def exists = fileExists 'TestAutomationProject'
					if (!exists){
						new File('TestAutomationProject').mkdir()
					}
					dir ('TestAutomationProject') {
						git url: 'http://localhost:3000/basil/MercuryTours.git'
					}
				}
			}
		}

		stage ('Sanity') {
			parallel {
				stage('Firefox') {
					steps {
						echo 'Run in Firefox'
						script {
							dir("TestAutomationProject") {
								try {
									bat 'mvn -f TestAutomationProject\\pom.xml clean test -Dcucumber.options="--tags @smoke01"'
								} catch (err) {
								} finally {
									publishHTML (target: [
									reportDir: 'TestAutomationProject/target/cucumber-reports',
									reportFiles: 'index.html',
									reportName: "SmokeFirefox"
									])
								}
							}
						}
					}
				}

				stage('Chrome') {
					steps {
						echo 'Run in Chrome'
						script {
							dir("TestAutomationProject") {
								try {
									bat 'mvn -f TestAutomationProject\\pom.xml clean test -Dcucumber.options="--tags @smoke02"'
								} catch (err) {
								} finally {
									publishHTML (target: [
									reportDir: 'TestAutomationProject/target/cucumber-reports',
									reportFiles: 'index.html',
									reportName: "SmokeChrome"
									])
								}
							}
						}
					}
				}
			}
		}

		stage ('Report') {
			steps {
				echo 'Generate Report'
				script {
					def exists = fileExists 'TestAutomationProject'
					if (exists){
						dir ('TestAutomationProject') {
							publishHTML (target: [
								reportDir: 'TestAutomationProject/target/cucumber-reports',
								reportFiles: 'index.html',
								reportName: "SmokeChrome"
							])
						}
					}
				}
			}
		}

	}
}